### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by ishaniGupta27** [felixe/idsEventGenerator#3]
Hi,
I think 

sudo apt-get install libcurl4-openssl-dev is the dependency.
Also, for compilation I needed
sudo g++ -std=c++11 -lcurl idsEventGenerator.cpp **-lcurl**

**Comment by felixe** [comment]
thx for the comment.
I only generally stated that libcurl is needed but didnt want to list the lib name for every OS. 
But I added your command as an example (consistency i guess ;-) as i already proposed apt-get with exrex)
